import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const skillDir = resolve(scriptDir, "..");
const projectRoot = resolve(skillDir, "../..");
const skillPath = resolve(skillDir, "SKILL.md");
const outputPath = resolve(projectRoot, "shared/generate/generated-skill.ts");

const source = await readFile(skillPath, "utf8");
const match = source.match(
  /<!-- BLAHBLAH_SPEC_START -->\s*```json\s*([\s\S]*?)\s*```\s*<!-- BLAHBLAH_SPEC_END -->/,
);
if (!match) throw new Error("SKILL.md is missing the BLAHBLAH spec block");

const rawSpec = JSON.parse(match[1]);
const requiredMaps = [
  "modes",
  "modeMoodExamples",
  "mentalStates",
  "compactMentalStates",
  "lengths",
  "mechanisms",
  "mechanismPools",
];
const requiredArrays = ["runtimeInstruction", "common", "qualityGate"];
for (const key of requiredArrays) {
  if (!Array.isArray(rawSpec[key]) || rawSpec[key].length === 0) {
    throw new Error(`SKILL.md ${key} must be a non-empty array`);
  }
}
for (const key of requiredMaps) {
  if (!rawSpec[key] || typeof rawSpec[key] !== "object") {
    throw new Error(`SKILL.md spec is missing ${key}`);
  }
}

const spec = {
  ...rawSpec,
  runtimeInstruction: rawSpec.runtimeInstruction.join("\n"),
  common: rawSpec.common.join("\n"),
  qualityGate: rawSpec.qualityGate.join("\n"),
};
const sha256 = createHash("sha256").update(source).digest("hex");
const generated = `/* Generated by skills/blahblah-generator/scripts/compile.mjs.
 * Do not edit this file; edit SKILL.md and run npm run prepare:skill. */

export const SKILL_SOURCE = ${JSON.stringify(source)};
export const SKILL_SHA256 = ${JSON.stringify(sha256)};
export const SKILL_SPEC = ${JSON.stringify(spec, null, 2)} as const;
`;

await writeFile(outputPath, generated, "utf8");
console.log(`Compiled blahblah-generator skill ${sha256.slice(0, 12)}`);
